# https://travis-ci.org/jleclanche/fireplace
sudo: false
language: python

python: "3.6"
cache: pip

env:
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=benchmark

install:
  - pip install tox

script:
  - tox
