# https://travis-ci.org/jleclanche/fireplace
sudo: false
language: python

python: "3.8"
cache: pip

env:
  - TOXENV=py38
  - TOXENV=flake8
  - TOXENV=benchmark

install:
  - pip install tox

script:
  - tox
