# https://travis-ci.org/#!/jleclanche/fireplace
sudo: false
language: python
python:
  - 3.5
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python3.5
install:
  - pip install -r requirements.txt
  - pip install .
script: py.test
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
