##
# Internal fireplace tags

KILLED_THIS_TURN = -10
ALWAYS_WINS_BRAWLS = -11
CANT_OVERLOAD = -12
EXTRA_BATTLECRIES = -13
DISCARDED = -14
MURLOCS_COST_HEALTH = -15
CAST_ON_FRIENDLY_CHARACTERS = -16
UNLIMITED_ATTACKS = -17
ELEMENTAL_PLAYED_LAST_TURN = -18
