TARGET_NONE = 0x0
TARGET_FRIENDLY = 0x1
TARGET_ENEMY = 0x2
TARGET_ANY = TARGET_FRIENDLY | TARGET_ENEMY
TARGET_MINION = 0x4
TARGET_HERO = 0x8
TARGET_CHARACTER = TARGET_MINION | TARGET_HERO
TARGET_ALL = 0x10

TARGET_FRIENDLY_HERO = TARGET_FRIENDLY | TARGET_HERO
TARGET_FRIENDLY_MINION = TARGET_FRIENDLY | TARGET_MINION
TARGET_FRIENDLY_MINIONS = TARGET_FRIENDLY_MINION | TARGET_ALL
TARGET_FRIENDLY_CHARACTERS = TARGET_FRIENDLY_HERO | TARGET_FRIENDLY_MINIONS

TARGET_ENEMY_HERO = TARGET_ENEMY | TARGET_HERO
TARGET_ENEMY_MINION = TARGET_ENEMY | TARGET_MINION
TARGET_ENEMY_MINIONS = TARGET_ENEMY_MINION | TARGET_ALL
TARGET_ENEMY_CHARACTERS = TARGET_ENEMY_HERO | TARGET_ENEMY_MINIONS

TARGET_ANY_MINION = TARGET_FRIENDLY_MINION | TARGET_ENEMY_MINION
TARGET_ANY_HERO = TARGET_FRIENDLY_HERO | TARGET_ENEMY_HERO
TARGET_ALL_MINIONS = TARGET_FRIENDLY_MINIONS | TARGET_ENEMY_MINIONS
TARGET_ALL_CHARACTERS = TARGET_ALL_MINIONS | TARGET_ANY_HERO
